[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "report-urssi-fellowship-2025"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks.build]
description = "Build report as static HTML website"
cmd = "myst build --html"
cwd = "report"

[tasks.pdf]
description = "Build PDF export of report"
cmd = "myst build --pdf"
cwd = "report"

[tasks.clean]
description = "Remove exports, temp files and installed templates"
cmd = "myst clean --yes"
cwd = "report"

[tasks.serve]
cmd = "myst start"
cwd = "report"
description = "Start a local server to preview the report"

[tasks.start]
depends-on = ["pdf", "serve"]

[dependencies]
mystmd = ">=1.7.0,<2"
typst = ">=0.14.1,<0.15"

[feature.analysis.dependencies]
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
notebook = ">=7.5.0,<8"
jupyterlab = ">=4.5.0,<5"

[feature.analysis.tasks.lab]
cmd = "jupyter lab"

[environments]
analysis = { features = ["analysis"], no-default-feature = true }
